# Generated by Django 3.1.6 on 2021-02-10 16:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(db_column='start_date', default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(db_column='end_date', null=True)),
                ('price', models.DecimalField(db_column='price', decimal_places=2, default=200, max_digits=10)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'db_table': 'appointment',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=150)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=150)),
            ],
            options={
                'verbose_name': 'Physician',
                'verbose_name_plural': 'Physicians',
                'db_table': 'physician',
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(db_column='value', decimal_places=2, default=200, max_digits=10)),
                ('appointment', models.ForeignKey(db_column='appointment_id', on_delete=django.db.models.deletion.PROTECT, related_name='Charges', to='api.appointment')),
            ],
            options={
                'verbose_name': 'Charge',
                'verbose_name_plural': 'Charges',
                'db_table': 'charge',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.PROTECT, related_name='Appointments', to='api.patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='physician',
            field=models.ForeignKey(db_column='physician_id', on_delete=django.db.models.deletion.PROTECT, related_name='Appointments', to='api.physician'),
        ),
    ]
